[package]
name = "smarter-scan"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
clap = { version = "4.5.38", features = ["derive"] }
maud = { version = "0.27.0", features = ["axum"] }
serde = { version = "1.0.219", features = ["derive"] }
tokio = { version = "1.45.0", features = ["rt-multi-thread", "fs"] }
bjw-db = { git = "https://github.com/wyv3rn/bjw-db.git", version = "0.1.0", features = ["derive"] }
bjw-db-derive = { git = "https://github.com/wyv3rn/bjw-db.git", version = "0.1.0" }
chrono = "0.4.41"
